version: '3'
services:
  nestjs:
    container_name: nestjs
    depends_on:
      - postgres
      - mongodb
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000

  postgres:
    container_name: nest-postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=nestjs
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - nest-network

  mongodb:
    container_name: nest-mongodb
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=nestjs
    ports:
      - 27017:27017
    volumes:
      - ./data/mongodb:/data/db
    restart: always
    networks:
      - nest-network

networks:
  nest-network:
    driver: bridge
