export default {
  PORT: 'PORT',
  API_VERSION: 'API_VERSION',
  JWT_SECRET: 'JWT_SECRET',
  JWT_EXPIRATION_TIME: 'JWT_EXPIRATION_TIME',

  MONGO_URI: 'MONGO_URI',
  MONGO_USER: 'MONGO_USER',
  MONGO_PASSWORD: 'MONGO_PASSWORD',
  MONGO_DB: 'MONGO_DB',
  MONGO_PORT: 'MONGO_PORT',
  MONGO_HOST: 'MONGO_HOST',
};
