export default {
  PORT: 'PORT',
  API_VERSION: 'API_VERSION',
  JWT_SECRET: 'JWT_SECRET',
  JWT_EXPIRATION_TIME: 'JWT_EXPIRATION_TIME',

  MONGO_URI: 'MONGO_URI',
  MONGO_USER: 'MONGO_USER',
  MONGO_PASSWORD: 'MONGO_PASSWORD',
  MONGO_DB: 'MONGO_DB',
  MONGO_PORT: 'MONGO_PORT',
  MONGO_HOST: 'MONGO_HOST',

  HOST: 'HOST',
  USER: 'USER',
  PASS: 'PASS',

  POSTGRES_USER: 'POSTGRES_USER',
  POSTGRES_PASSWORD: 'POSTGRES_PASSWORD',
  POSTGRES_HOST: 'POSTGRES_HOST',
  POSTGRES_PORT: 'POSTGRES_PORT',
  POSTGRES_DB: 'POSTGRES_DB'
}
